version: '3.9'

services:
  rest-service:
    container_name: sevenify-rest-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - .docker.env
    volumes:
      - "./src/:/usr/src/app/src/:ro"
    depends_on:
      rest-db:
        condition: service_healthy

  rest-db:
    container_name: sevenify-rest-k
    hostname: db
    ports:
      - "6001:3306"
    image: mysql:latest
    env_file:
      - .docker.env
    volumes:
      - "./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p{MYSQL_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20